### ISSUE TITLE
只能识别bottle吗

### ISSUE THREAD

**Issue by huayunhe** [muyuuuu/Flow-Detection#1]
这个只能识别水瓶吗，还是加入其他的数据集，也可以识别出来，比如说塑料袋，纸张之类的。

**Comment by muyuuuu** [comment]
emm，是的，因为数据集只有一个类别，所以我这个只识别 bottle。

如果数据集有其他类别，是可以做到的都识别的。另外的，我用自监督预训练的时候发现，只要不是背景，基本都能检测到，比如船上带有的后背镜等。

如果有多个类别，自监督还是这样操作不变。预训练的话，区分前背景吧，所有类别视为前景，背景依然是背景，做二分类。

**Comment by huayunhe** [comment]
yolox_flow.py中的文件_base_ = ["../_base_/schedules/schedule_1x.py", "../_base_/default_runtime.py"]没有找到原因

**Comment by huayunhe** [comment]
yolox_flow.py中的文件_base_ = ["../base/schedules/schedule_1x.py", "../base/default_runtime.py"]没有找到

**Comment by huayunhe** [comment]
center_loss.py中的cfg = Config.fromfile(args.config)的config配置那个文件😂

**Comment by huayunhe** [comment]
center_loss.py中的cfg = Config.fromfile(args.config)的config配置哪个文件😂

**Comment by muyuuuu** [comment]
这个，你需要安装完整的 mmdetection，然后在了解它基础的训练步骤后，使用我的配置文件就好了。安装链接：

https://github.com/open-mmlab/mmdetection
